### ISSUE TITLE
The `_useHeaderApiKey` is always be `true` when using API Key auth.

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#10]
Due to the logic of the existing code, the `_useHeaderApiKey` will never be `false`.

![image](https://github.com/mscraftsman/generative-ai/assets/88981/257618f9-66e9-4476-b0e2-d8d31d18369c)

It because `_useHeaderApiKey` is always `true`, so that the following code will never run.

```cs
text += "?key={apiKey}";
```

![image](https://github.com/mscraftsman/generative-ai/assets/88981/cdc925b1-cd0a-4765-9996-100f3f7b0a7a)

**Comment by jochenkirstaetter** [comment]
Thanks for pointing it out.
I might remove that source code soon. It's from the beginnings before I had knowledge of the HTTP header value.

Won't fix but most likely remove it. The original samples in the API documentation for REST and Google AI describe the URL query string parameter in length. Personally, I don't find it appealing to expose API keys in any kind of web server log files.

**Comment by jochenkirstaetter** [comment]
Remove in version 0.9.1
