### ISSUE TITLE
Hints for possible Exceptions

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#11]
Is it possible add `Exceptions` hints for public APIs?

For example:

![image](https://github.com/mscraftsman/generative-ai/assets/88981/9dc9f1cf-4650-4ff2-a3ca-0780fabdca43)

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 

Yes, of course. Partially, they already exist.
Primarily, giving information regarding `ArgumentNullException` and `NotSupportedException` which are also tested for.

```
            // Act & Assert
            await Assert.ThrowsAsync<ArgumentNullException>(() => model.GenerateContent(prompt));
```

Do you have a wish list of improvements? ;-)

**Comment by doggy8088** [comment]
For `GenerateContent` method, I don't know how to show it on my LINQPad query.

![image](https://github.com/mscraftsman/generative-ai/assets/88981/4be0bbd3-110f-468b-8f11-7c18c8960b20)

**Comment by jochenkirstaetter** [comment]
Hmm, it looks like the existing XMLDoc is not picked up properly. I have to investigate...

Sorry for the lack of description.

**Comment by doggy8088** [comment]
Related: https://github.com/mscraftsman/generative-ai/issues/21

I think this issue has been resolved.

**Comment by jochenkirstaetter** [comment]
Great, thanks for following up and checking.
