### ISSUE TITLE
`model.GetModel()` returned wrong `SupportedGenerationMethods`

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#13]
Here is [my code](https://share.linqpad.net/to7xwchk.linq):

```cs
async Task Main()
{
	var googleAI = new GoogleAI(apiKey: Util.GetPassword("GEMINI_API_KEY"));
	var model = googleAI.GenerativeModel(model: Model.Embedding).Dump();
	var response = await model.GetModel().Dump();
}
```

I don't know why. The `SupportedGenerationMethods` property seems wrong. The `model.GetModel()` call still think he is `models/gemini-pro` model?

![image](https://github.com/mscraftsman/generative-ai/assets/88981/93a09461-78cc-47fd-91ba-4c9fbfa6500c)

I do checked with the REST API call directly. The response is correct. I don't know why.

```json
{
  "name": "models/embedding-001",
  "version": "001",
  "displayName": "Embedding 001",
  "description": "Obtain a distributed representation of a text.",
  "inputTokenLimit": 2048,
  "outputTokenLimit": 1,
  "supportedGenerationMethods": [
    "embedContent"
  ]
}
```

**Comment by doggy8088** [comment]
I found the bug now. The default value of the `model` argument pass into `GetModel` should not fixed with `gemini-pro`. It should get value from `_model` by default.

![image](https://github.com/mscraftsman/generative-ai/assets/88981/a1396cc2-cd25-4d25-b8c8-481bb337c3a8)

**Comment by jochenkirstaetter** [comment]
Thanks for the catch. It shouldn't be an optional parameter after all.

I understand the assumption. The method itself is at the wrong location. It should not be a member of the model type but belonging to the IGenerativeAI interface.

Same for other methods like ListModels, CreateTunedModel, etc.

Those are currently at the wrong place.

Very good findings!
Thank you very much, @doggy8088
