### ISSUE TITLE
Provide full context for the HttpRequestException

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#19]
I wish there is an original response JSON content comes from the API response when there is an HttpRequestException thrown. This is for better debugging.

**Comment by jochenkirstaetter** [comment]
Good suggestion, @doggy8088 

That's coming with the improvements regarding logging.
Give me a bit of time to work this out.

**Comment by doggy8088** [comment]
Before logging been implemented, I think the exception issue might be able to improve at first.

**Comment by jochenkirstaetter** [comment]
Yes, agreed.
Now, that the Gemini API is fully implemented by the library, I'm looking into further improvements and stabilization.

**Comment by doggy8088** [comment]
Is it possible add an "InnerException" when throwing exception at Gemini API call failed?

**Comment by sebastianbk** [comment]
> Is it possible add an "InnerException" when throwing exception at Gemini API call failed?

I would really appreciate this as well.

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 and @sebastianbk 

The code does not catch and rethrow those exceptions, those are straight from the `HttpClient`. I'll see what I can do to improve the situation though.

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 and @sebastianbk 

This has been resolved and released in version [v1.6.5](https://github.com/mscraftsman/generative-ai/releases/tag/v1.6.5)
I hope this is helpful.

Cheers, JoKi
