### ISSUE TITLE
Assigning a API_KEY using model.ApiKey is not working

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#20]
Here is my code. It's not working. It should be a bug.

```cs
void Main()
{
    var googleAI = new GoogleAI(apiKey: "WRONG_API_KEY");
    var model = googleAI.GenerativeModel(model: Model.Gemini10Pro001);
    model.ApiKey = Util.GetPassword("GEMINI_API_KEY");
    model.GenerateContent("Tell me 4 things about Taipei. Be short.").Dump();
}
```

![image](https://github.com/mscraftsman/generative-ai/assets/88981/0cfc8267-5c39-42b6-a335-fa1bbb9fd59c)

I think bug is here:

![image](https://github.com/mscraftsman/generative-ai/assets/88981/25cbc904-617d-480c-aca2-71e738f6fb2f)

You should able to replace a new key there.

**Comment by jochenkirstaetter** [comment]
Interesting...
Last time I ran into an exception, now not.

Fixed in next release.

**Comment by doggy8088** [comment]
@jochenkirstaetter Awesome, pal! It works now. 👍
