### ISSUE TITLE
The `inheritdoc` XML comment can't appear in LINQPad

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#21]
I think this issue is related to LINQPad implementation. I [posted an issue](https://forum.linqpad.net/discussion/2463/intellisense-doesnt-work-with-inheritdoc#latest) in their forum. The LINQPad doesn't support [&lt;inheritdoc&gt;](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/xmldoc/recommended-tags?WT.mc_id=DT-MVP-4015686#inheritdoc) at this moment.

```cs
/// <inheritdoc cref="M:GenerativeModel.GenerateContent(request)" />
```

![image](https://github.com/mscraftsman/generative-ai/assets/88981/0a4d41e1-803a-471e-bf0c-d6526f32305d)

![image](https://github.com/mscraftsman/generative-ai/assets/88981/4ac0fa89-b38d-4550-89cb-5fb4a361fb51)

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 

They have been removed in latest release.
