### ISSUE TITLE
await model.ListFiles() get HTTP 403 (Forbidden)

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#22]
The code:

```cs
#nullable enable

async Task Main()
{
    var googleAI = new GoogleAI(apiKey: Util.GetPassword("GEMINI_API_KEY"));

    // var model = googleAI.GenerativeModel(model: Model.Gemini15Pro);
    var model = googleAI.GenerativeModel(model: Model.Gemini10Pro001);
	
    var files = await model.ListFiles();
	
    files.Dump();
}
```

The result:

![image](https://github.com/mscraftsman/generative-ai/assets/88981/4eb028f5-b2ed-4f2f-abbe-ea403130a2cc)

I don't know what's the exact problem I met. I can't see response body (JSON) from the Gemini API.

Related: https://github.com/mscraftsman/generative-ai/issues/6 and https://github.com/mscraftsman/generative-ai/issues/19

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 
Did you upload any files beforehand?

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 
Do you have access to the Gemini 1.5 API and File API?

**Comment by jochenkirstaetter** [comment]
Could you please check whether you can make a REST API call using cURL?

```
GET https://generativelanguage.googleapis.com/v1beta/files?key=$GOOGLE_API_KEY
```

I assume that you might not have access to the API endpoints (yet).

**Comment by doggy8088** [comment]
I used the wrong key. The key to use must be created under the GCP Project that enabled for Gemini 1.5 Pro.
