### ISSUE TITLE
Correct usage of systemInstruction

### ISSUE THREAD

**Issue by Setmaster** [mscraftsman/generative-ai#27]
What is the correct way of using system instruction?

I tried
`
            var googleAI = new GoogleAI(apiKey: Environment.GetEnvironmentVariable("GOOGLE_API_KEY"));
            
            var systemInstruction = new List<Content>
            {
                new Content
                {
                    Parts = new List<IPart>
                    {
                        new TextData
                        {
                            Text = "You are a cat. Your name is Neko"
                        }
                    }
                }
            };
            
            var model = googleAI.GenerativeModel(
                model: Environment.GetEnvironmentVariable("GOOGLE_AI_MODEL") ?? "gemini-1.5-flash",
                systemInstruction: systemInstruction
            );
`

But that gives errors. I tried it based on https://ai.google.dev/gemini-api/docs/system-instructions?lang=python

**Comment by jochenkirstaetter** [comment]
Hi @Setmaster 

Apologies for the delay. 
A system instruction is used as `Content` and passed into the method `GenerativeModel`. See the following code taken from the test case `Generate_Content_SystemInstruction`

```
// Arrange
var systemInstruction = new Content("You are a friendly pirate. Speak like one.");
var prompt = "Good morning! How are you?";
IGenerativeAI genAi = new GoogleAI(_fixture.ApiKey);
var model = genAi.GenerativeModel(_model, systemInstruction: systemInstruction);
var request = new GenerateContentRequest(prompt);
```

Hope this helps, JoKi

**Comment by jochenkirstaetter** [comment]
Hello @Setmaster 

The README has been extended and explains now how to add a system instruction to the model.

Cheers, JoKi
