### ISSUE TITLE
400 ERROR when used on Azure. Localhost is fine

### ISSUE THREAD

**Issue by lunar-safari** [mscraftsman/generative-ai#28]
I've built an app that uses the Gemini AI api, and it works great locally on my machine on localhost.

When I publish the app to Azure I keep getting 400 errors when my code hits the AI

`System.AggregateException: One or more errors occurred. (Response status code does not indicate success: 400 (Bad Request).)---> System.Net.Http.HttpRequestException: Response status code does not indicate success: 400 (Bad Request).at System.Net.Http.HttpResponseMessage.EnsureSuccessStatusCode()at Mscc.GenerativeAI.GenerativeModel.GenerateContent(GenerateContentRequest request)at Mscc.GenerativeAI.GenerativeModel.GenerateContent(String prompt, GenerationConfig generationConfig, List`1 safetySettings, List`1 tools, ToolConfig toolConfig)`

My code is real simple. It fails on the simple example

```
     string apiKey = "blah blah";
     var prompt = "Write a story about a magic backpack.";
     var googleAI = new GoogleAI(apiKey: apiKey);
     var model = googleAI.GenerativeModel(model: Model.Gemini15Flash);
     var response = model.GenerateContent(prompt).Result;
     Console.WriteLine(response.Text);
```

In Azure, I've set the key to 'unrestricted' and it still fails.

![image](https://github.com/user-attachments/assets/ec24bebe-3999-423a-8ad0-bef9c4a3f097)

Is there a setting I need to change on Azure? Or the Google API settings?

I have billing enabled for the API.

Thanks

**Comment by jochenkirstaetter** [comment]
Hello @lunar-safari 

How did you solve this issue?
Apologies for not responding to it earlier.

Regards, JoKi
