### ISSUE TITLE
gemini release 3 new models 

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#30]
1. `gemini-1.5-pro-exp-0827`
2. `gemini-1.5-flash-8b-exp-0827`
3. `gemini-1.5-flash-exp-0827`

Ref 1: https://x.com/OfficialLoganK/status/1828480081574142227

Ref 2: https://www.unite.ai/google-releases-three-new-experimental-gemini-models/

**Comment by doggy8088** [comment]
I see that these three Models have [already been added](https://github.com/mscraftsman/generative-ai/commit/68331fe004db0d4ba18be75ea9e55815d9296891).

**Comment by jochenkirstaetter** [comment]
Hello @doggy8088 

Thank you so much for the references to new models. Really appreciate your support.
Yes, I added them with Release 1.6.0 among others.

Furthermore, the model class is not an enumeration but provides constants to the model names (I'm terrible at memorizing). Any method accepting a model is based on `string` data type. In case that a model is not present as a constant one can use the value as string directly.

Thanks again, JoKi
