### ISSUE TITLE
New Gemini models released: Gemini-1.5-Pro-002 and Gemini-1.5-Flash-002

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#31]
Google just released two upgraded Gemini 1.5 models:

1. Gemini 1.5 Pro 002 ( `gemini-1.5-pro-002` )
2. Gemini 1.5 Flash 002 ( `gemini-1.5-flash-002` )

Related: https://developers.googleblog.com/en/updated-production-ready-gemini-models-reduced-15-pro-pricing-increased-rate-limits-and-more/

**Comment by jochenkirstaetter** [comment]
Hello @doggy8088 
Thanks for the info. Please see release 1.6.3 ;-)
