### ISSUE TITLE
Request to add FileResource.Status field and enhance GenerateContent() to return detailed error information

### ISSUE THREAD

**Issue by paveliciousness** [mscraftsman/generative-ai#33]
Request to extent API:

Add a `Status` field to the `FileResource` class to track the current status of the file resource.

![1](https://github.com/user-attachments/assets/4de9cfea-7974-47f4-abc6-fe7b257f8ed9)

Modify the `GenerateContent()` method to return detailed error information.

![2](https://github.com/user-attachments/assets/99d81659-05fe-49e5-9f33-8fbd8d7e724b)

**Comment by jochenkirstaetter** [comment]
Hello @paveliciousness 

Thanks for the suggestion. I'm currently working on general integration of `ILogger` to provide more detailed output. Would this be an alternative or addition to your suggestion?

Cheers, JoKi

**Comment by paveliciousness** [comment]
Hi @jochenkirstaetter,

Thank you for the update! Integrating ILogger sounds promising and could serve as a solid alternative. However, I believe that including JSON fields in custom exceptions or returning JSON in the exception messages would enhance our code-level handling.

Best regards,
Pavel

**Comment by jochenkirstaetter** [comment]
Hi @paveliciousness

Thanks for your feedback.
I'm working on more detailed info in case of an unexpected behaviour.

Using custom exceptions is an interesting approach which I was considering myself. Thanks for your suggestion.

Cheers, JoKi

**Comment by jochenkirstaetter** [comment]
Release in https://github.com/mscraftsman/generative-ai/releases/tag/v1.6.5
