### ISSUE TITLE
HttpRequestException when used on Windows with .Net 8.0

### ISSUE THREAD

**Issue by MaiRat** [mscraftsman/generative-ai#34]
The examples cause the following exception when used:

System.Net.Http.HttpRequestException: 'An internal error has occurred. ConfigurationLoadCredential failed: Unknown (0x80090331) (generativelanguage.googleapis.com:443)'

If I set the 'DefaultVersionPolicy' to 'HttpVersionPolicy.RequestVersionExact' (in GenerativeModel.cs) to force HTTP/1.1, it works. Also works with HTTP/2.0. So, it seems to be an issue with HTTP/3.0?!

**Comment by jochenkirstaetter** [comment]
Hi @MaiRat 

Thanks for flagging this. I'll have a look.

As for HTTP/3.0, there might be pre-requisite depending on the OS as described by Microsoft. The HttpClient uses libmsquic internally. See here: https://learn.microsoft.com/en-us/dotnet/fundamentals/networking/quic/quic-overview

**Comment by jochenkirstaetter** [comment]
Hello @MaiRat 

Could it be that you're using an older version?
The initialization of the HttpClient had been changed on 19th September. See here:

https://github.com/mscraftsman/generative-ai/blob/77876ad8252461879d8236fed22a4018cd76d9b4/src/Mscc.GenerativeAI/GenerativeModel.cs#L52-L61

This was released in version 1.6.2.

**Comment by MaiRat** [comment]
Hello @jochenkirstaetter,

I am using Version 1.6.4. By adding the following in my code, all is fine (without HTTP3 Support):

AppContext.SetSwitch("System.Net.SocketsHttpHandler.Http3Support", false);

Otherwise, I can't get QUIC to work. I am on Windows 11 24H2, latest updates, latest Studio 2022 17.11.5. I added all mentioned RegKeys from the MSQUIC info-site, copied the dll in my folder and the windows\system32 folder (correct architecture), but nothing works (dism with checkimagehealth and sfc doesnt find any issues)

**Comment by jochenkirstaetter** [comment]
For reference, it's an issue with how the QuicConnection is currently implemented.

https://github.com/dotnet/runtime/issues/87478

**Comment by jochenkirstaetter** [comment]
And it seems to be fixed for .NET 9.0
https://github.com/icerpc/icerpc-csharp/pull/3991

**Comment by jochenkirstaetter** [comment]
Disabled HTTP/3 & Quic due to .NET 8.0 and earlier.
Remains enabled in .NET 9.0

See [Release v1.8.0](https://github.com/mscraftsman/generative-ai/releases/tag/v1.8.0)
