### ISSUE TITLE
GenerativeModel.UploadFile locks the uploaded file.

### ISSUE THREAD

**Issue by rsmithsa** [mscraftsman/generative-ai#35]
Thanks for a great library! One minor issue I've picked up is that "UploadFile" doesn't dispose of the FileStream it uses. This means that it tends to keep the file open after upload.

It makes a workflow like this more or less impossible to implement cleanly:

1. Fetch file to a temporary location
2. GenerativeModel.UploadFile
3. Delete the file from temp

Just wrapping the FileStream you create in a using block would probably do the trick.

Additionally if possible having an UploadFile overload which supports streams rather than files would be amazing - happy to log this as another ticket if you'd like.

**Comment by jochenkirstaetter** [comment]
Hello @rsmithsa 
Thanks for looking into this and providing a solution. Yes, you're right on the dispose and overload. Would be happy to merge those changes.

Cheers, JoKi

**Comment by rsmithsa** [comment]
Thanks, I'll create a PR for the stream based overload as well.

**Comment by jochenkirstaetter** [comment]
New issue #38 has been created. Thanks

**Comment by jochenkirstaetter** [comment]
Released in https://github.com/mscraftsman/generative-ai/releases/tag/v1.6.5
