### ISSUE TITLE
how to add history in model 

### ISSUE THREAD

**Issue by sparklemisery** [mscraftsman/generative-ai#41]
i build a website that use this model api for chatbox but it seem doesn't have any method for add content between user and system .

        public async Task<JsonResult> getmessage(string message)
        {
            IGenerativeAI genAi = new GoogleAI(apiKey);
            var model = genAi.GenerativeModel(Model.Gemini15Pro, systemInstruction: systemInstruction);
            var request = new GenerateContentRequest(message);
            var response = await model.GenerateContent(request);
            return Json(response.Text);
            
        }

**Comment by jochenkirstaetter** [comment]
Hi @sparklemisery 

Use the `StartChat()` method to initiate a Chat session with history. See [here in the README](https://github.com/mscraftsman/generative-ai#chat-conversations) about Chat Conversations.

The method optionally accepts a history of content to restore a previously stored conversation.
See https://github.com/mscraftsman/generative-ai/blob/7886f455e996a8dd77e80f36b886c3a69332a70a/src/Mscc.GenerativeAI/GenerativeModel.cs#L1343 for reference.

Regards, JoKi

**Comment by jochenkirstaetter** [comment]
Hi @sparklemisery 

I hope you could manage it. Without further follow up I'm going to close this issue though.
