### ISSUE TITLE
Gemini Experimental 1114

### ISSUE THREAD

**Issue by shankarvashist** [mscraftsman/generative-ai#45]
Can you please add new model Gemini Experimental 1114, which has been released recently. Thanks.

**Comment by jochenkirstaetter** [comment]
Hello @shankarvashist,

Thanks for the hint, yes, will update it today.

FYI, you can also pass the model name as a string into the methods. The static class Model with the constants is a trick of laziness only. 😉

**Comment by jochenkirstaetter** [comment]
Hi @shankarvashist 

Also, I'm a bit intrigued by the following information when you query the details of the model.
```
      "name": "models/gemini-exp-1114",
      "version": "exp-1114",
      "displayName": "Gemini Experimental 1114",
      "description": "Mid-size multimodal model that supports up to 2 million tokens",
      "inputTokenLimit": 32767,
```
Although the description speaks of 2M tokens, the input  limit seems to be 32k only.

**Comment by jochenkirstaetter** [comment]
Hi @shankarvashist 

New release [v1.9.2](https://github.com/mscraftsman/generative-ai/releases/tag/v1.9.2) has been released containing the new experimental model as constant.

Thanks, JoKi

**Comment by shankarvashist** [comment]
Hi Jochen,

Thanks for your reply. Well noted that the string can be passed :-)
Also, I see in your other response that 1.9.2 has the new model added.
 This model, in google ai studio clearly specifies 32K tokens only.  Seems
they are experimenting with another approach which may be more resource
intensive.. I'm still checking this one out..
Many Thanks..

Best Regards,
Shankar Vashist.

**Comment by jochenkirstaetter** [comment]
Hi @shankarvashist 

This new experimental model also has only 32k input tokens according to the model details.
```
      "name": "models/gemini-exp-1114",
      "version": "exp-1114",
      "displayName": "Gemini Experimental 1114",
      "description": "Mid-size multimodal model that supports up to 2 million tokens",
      "inputTokenLimit": 32767,
      "outputTokenLimit": 8192,
      "supportedGenerationMethods": [
        "generateContent",
        "countTokens"
      ],
      "temperature": 1,
      "topP": 0.95,
      "topK": 64,
      "maxTemperature": 2
```
