### ISSUE TITLE
New model released: learnlm-1.5-pro-experimental

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#46]
![image](https://github.com/user-attachments/assets/b8eb7fc7-fe80-49de-afd0-dd6df0fa1aad)

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 

Thanks for the hint. It's already available in the lastest release [v1.9.4](https://github.com/mscraftsman/generative-ai/releases/tag/v1.9.4)

Cheers, JoKi
