### ISSUE TITLE
New model released: gemini-exp-1121

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#47]
![image](https://github.com/user-attachments/assets/3eb8c1a5-d783-4197-9c09-4d3c77a8a787)

The speed of releasing new models from Google is really rushing! 😄

**Comment by jochenkirstaetter** [comment]
Hi @doggy8088 

New release [v1.9.5](https://github.com/mscraftsman/generative-ai/releases/tag/v1.9.5) is available.

Cheers JoKi
