### ISSUE TITLE
typeload exception for microsoft package

### ISSUE THREAD

**Issue by sapsari** [mscraftsman/generative-ai#49]
added nuget package to a .net standard 2.0 library project
exception is thrown when constructor of GeminiChatClient is being about to be called

System.TypeLoadException: 'Method 'GetService' in type 'Mscc.GenerativeAI.Microsoft.GeminiChatClient' from assembly 'Mscc.GenerativeAI.Microsoft, Version=1.9.4.0, Culture=neutral, PublicKeyToken=null' does not have an implementation.'

**Comment by jochenkirstaetter** [comment]
Hi @sapsari 

Thanks for reporting this issue.

Does the same problem occur with the latest preview package? It's [2.0.1-preview](https://www.nuget.org/packages/Mscc.GenerativeAI.Microsoft/2.0.1-preview).

I reverted back to preview/prerelease packages based on good practices for NuGet packages having dependencies to other preview packages, like here `Microsoft.Extensions.AI`, which should not be versioned as regular package.

Apologies, my mistake.

**Comment by jochenkirstaetter** [comment]
Hi again,

The package README has a sample how to use the package and types for Chat and Embedding.
https://github.com/mscraftsman/generative-ai/tree/main/src/Mscc.GenerativeAI.Microsoft

Hope this helps.

**Comment by sapsari** [comment]
> Does the same problem occur with the latest preview package? It's [2.0.1-preview](https://www.nuget.org/packages/Mscc.GenerativeAI.Microsoft/2.0.1-preview).

Tried this and it works, thanks
