### ISSUE TITLE
The original usage seems broken: new GenerativeModel(...)

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#5]
Here is my code:

```cs
async Task Main()
{
	var model = new GenerativeModel(apiKey: Util.GetPassword("GEMINI_API_KEY"), model: Model.GeminiPro);

	var prompt = "I love Taipei.";

	var response = await model.GenerateContent(prompt);

	response.Text.Dump();
}
```

LINQPad Query: <https://share.linqpad.net/s5ftv46u.linq>

Screenshot:

![image](https://github.com/mscraftsman/generative-ai/assets/88981/0cb74563-6c35-4343-96d6-fdc1f778cf47)

**Comment by jochenkirstaetter** [comment]
You got an HTTP 429 Too many requests.

You exceeded the default limit 60 qpm (queries per minute).

**Comment by doggy8088** [comment]
I know the limitation of the 60 QPM. The point is that, I am NOT request that much at that moment. The Google AI Gemini API will returned HTTP 429 from time to time. Unknown reason! Don't you met that before?

**Comment by jochenkirstaetter** [comment]
Hardly.
However, that's an external issue which I cannot control in the package itself. That's probably something that could be handled by a Retry pattern/approach. There are times when Google AI has too many loads and rejects calls even though you might be below the 60 QPMs. It's discussed among other developers, too.

**Comment by jochenkirstaetter** [comment]
Considering this as a use case of #2
