### ISSUE TITLE
It seems that Google has removed the 'Enable Enhanced Civic Answers' option.

### ISSUE THREAD

**Issue by Jiang3906** [mscraftsman/generative-ai#50]
In the 1.5 pro AND 1.5 flash.

![image](https://github.com/user-attachments/assets/e84fca3c-c6bd-4b19-a8b0-a5c4597e82d5)

**Comment by jochenkirstaetter** [comment]
Hi @Jiang3906 

Looking at the discovery response for Generatve Language API it is still listed as a property of the `generationConfig` object. Hence I'll leave it in there for now.

![image](https://github.com/user-attachments/assets/4b58107a-a13c-4892-9a4c-5f9188e93f20)

You're right that it has been removed from the safety settings in Google AI Studio though.
