### ISSUE TITLE
Unknown error due to some settings

### ISSUE THREAD

**Issue by doggy8088** [mscraftsman/generative-ai#7]
The following code will produce `Response status code does not indicate success: 400 (Bad Request).` error. I have no idea.

```cs
async Task Main()
{
	var googleAI = new GoogleAI(apiKey: Util.GetPassword("GEMINI_API_KEY"));
	var model = googleAI.GenerativeModel(model: Model.GeminiPro,
		generationConfig: new GenerationConfig()
		{
			TopK = 1,
			TopP = 1,
			Temperature = 0.9f
		},
		safetySettings: new List<SafetySetting>()
		{
			new SafetySetting() { Category = HarmCategory.HarmCategoryHarassment, Threshold = HarmBlockThreshold.BlockOnlyHigh },
			new SafetySetting() { Category = HarmCategory.HarmCategoryHateSpeech, Threshold = HarmBlockThreshold.BlockOnlyHigh },
			new SafetySetting() { Category = HarmCategory.HarmCategorySexuallyExplicit, Threshold = HarmBlockThreshold.BlockOnlyHigh },
			new SafetySetting() { Category = HarmCategory.HarmCategoryDangerousContent, Threshold = HarmBlockThreshold.BlockOnlyHigh }
		});

	var count = await model.CountTokens("Hello World");
	count.Dump();
}
```

LINQPad Query: <https://share.linqpad.net/entk5npb.linq>

**Comment by doggy8088** [comment]
I know the root cause now. The `generationConfig` and the `safetySettings` affected its request payload. That's invalid.

Here is what I think. The technical details should be hidden from the library user. The model should be reuse between generatecontent and counttokens. So maybe we can change `CountTokens` a bit that remove these two parts of the payload (`generationConfig` and the `safetySettings`) from the request automatically?

**Comment by jochenkirstaetter** [comment]
Is this related to #8 while using SafetySettings associated with PaLM 2 models?

**Comment by jochenkirstaetter** [comment]
New version 0.9.1 should make it clearer.

Plus, there is the official documentation about [Safety settings in Gemini](https://ai.google.dev/docs/safety_setting_gemini) that apply.

Hope this helps. Closing the issue (for now).

**Comment by jochenkirstaetter** [comment]
Cool, thanks for the feedback.
Actually, you can use both locations to specify `GenerationConfig` and `SafetySettings`.

The ones you configure at the model level apply to all requests following whereas the attributes you pass into a request are for that request only. See [GenerateContent(string)](https://github.com/mscraftsman/generative-ai/blob/22a5ab0e899a9bda7ef23decfa5039b75bf3165c/src/Mscc.GenerativeAI/GenerativeModel.cs#L520-L531) as an example.

Hmm, just noticed that same is currently missing with `GenerateContent(request)`. That method should have the following block.

```
            request.GenerationConfig ??= _generationConfig;
            request.SafetySettings ??= _safetySettings;
            request.Tools ??= _tools;
```

Going to add this and to `GenerateContentStream`, too.
